plenty of bug fixes

diff --git a/bootstrap-linux b/bootstrap-linux
--- a/bootstrap-linux
+++ b/bootstrap-linux
@@ -1,35 +1,43 @@
 #!/bin/bash
 # Bootstraps a Linux machine for an initial Puppet run.
 # Supports CentOS 5 and Ubuntu 12.04.
-# Handles configuration of up to two IP addresses
-
+#
+# 2013.07.17 - apowers : significant rewrite, better error checking and help,
+#             prompts for missing prameters,
+#             remove secondary interface configuration
+#
 function banner {
     echo
     echo "Usage (static IP addresses):"
-    echo "    $0 [-m] -n fqdn -f eth0_IP [-b eth1_IP] [-p puppetmaster] -r ns1 [-s ns2]"
+    echo "    $0 [-k] -n fqdn [-f eth0_IP|-d] [-p puppetmaster] -r ns1 [-s ns2]"
     echo
-    echo "Usage (DHCP):"
-    echo "    $0 [-m] -n fqdn -d [-p puppetmaster]"
+    echo "  -k              : regenerate SSH host keys"
+    echo "  -n fqdn         : fully-qualifed host name"
+    echo "  -f eth0_ip      : IP address for eth0 interface"
+    echo "  -d              : use DHCP to configure eth0"
+    echo "  -p puppetmaster : name of the puppetmaster, defaults to 'puppet'"
+    echo "  -r ns1          : IP address of primary DNS server"
+    echo "  -s ns1          : IP address of secondary DNS server"
     echo
-    echo "Help:"
-    echo "    $0 -h"
+    echo "This script assumes a /24 network with the gateway at .1"
+    echo "Hostname and IP address must be manually registered in DNS."
     echo
-    echo "Hostname and IP address must already be registered in DNS."
     exit 1
 }
 
-(
+#========================================================================
 # Parse options:
 ns2=''
 eth1_ip=''
-maintain_ip='off'
-while getopts "hdmp:n:f:b:r:s:" flag
+puppetmaster='puppet'
+
+while getopts "hdmkp:n:f:b:r:s:" flag
 do
   case $flag in
     b) eth1_ip=$OPTARG ;;
-    d) dhcp='on' ;;
+    d) dhcp=1 ;;
     f) eth0_ip=$OPTARG ;;
-    m) maintain_ip='on' ;;
+    k) ssh_keygen=1;;
     n) fqdn=$OPTARG ;;
     p) puppetmaster=$OPTARG ;;
     r) ns1=$OPTARG ;;
@@ -55,49 +63,48 @@ fi
 
 if [ $distro == 'Ubuntu' -a -z "$ns1" -a -z "$dhcp" ] ; then
   echo "INFO: No nameserver provided with static IP address."
-  echo "      Using nameservers from resolv.conf"
-  ns1=`grep nameserver /etc/resolv.conf|awk '{print $2}'`
+  echo -n "      Using nameservers from resolv.conf: "
+  ns1=`grep nameserver /etc/resolv.conf|head -n1|awk '{print $2}'`
+  echo $ns1
   while [ "$ns1" == '' -o "$ns1" == '127.0.0.1' ] ; do
     echo "WARNING: No nameserver provided."
-    echo -n "Enter nameserver IP address:" ; read ns1
+    echo -n "Enter nameserver IP address: " ; read ns1
   done
 fi
 
 if [ -z $fqdn ] ; then
   echo "INFO: No fully-qualified domain name given."
-  echo "      Using current hostname."
+  echo -n "      Using current hostname: "
   fqdn=`hostname --fqdn`
-  while [ "$fqdn" == 'ubuntu' -o "$fqdn" == 'centos' ] ; do
+  echo $fqdn
+  hostname=$(echo $fqdn|awk -F. '{print $1}')
+  while [ "$hostname" == 'ubuntu' -o "$hostname" == 'centos' ] ; do
     echo "WARNING: System has default name."
-    echo -n "Enter fully-qualified host name:" ; read fqdn
+    echo -n "Enter fully-qualified host name: " ; read fqdn
   done
 fi
 
 if [ -z "$eth0_ip" -a -z "$dhcp" ] ; then
   echo "INFO: No IP address given and DHCP not requested."
-  echo "      Using IP address configured on eth0."
-  eth0_ip=`/sbin/ifconfig eth0 2>/dev/null| grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
-  until echo $etho0_ip|egrep '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
-    echo "WARNING: Could not determine IP address of eth0."
-    echo -n "Enter host IP address:" ; read eth0_ip
+  echo -n "      Using IP address configured on eth0: "
+  eth0_ip=`/sbin/ifconfig eth0 2>/dev/null|grep "inet addr"|awk -F: '{print $2}'|awk '{print $1}'`
+  echo $eth0_ip
+# The 250 address is reserved for build templates
+  if echo $eth0_ip|egrep -q '\.250$' ; then eth0_ip='' ; fi
+  until echo $eth0_ip|egrep -q '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ; do
+    echo "WARNING: Invalid IP address for eth0."
+    echo -n "Enter host IP address or 'dhcp': " ; read eth0_ip
+    if [ "$eth0_ip" == 'dhcp' ] ; then dhcp=1 ; break ; fi
   done
 fi
 
-# We are assuming that the netmask is 255.255.255.0 and the last octet of the
-# gateway is .1.
-
-netmask="255.255.255.0"
-
-eth0_network=$(echo $eth0_ip | sed 's/\.[0-9]*$/.0/')
-eth0_broadcast=$(echo $eth0_ip | sed 's/\.[0-9]*$/.255/')
-eth0_gateway=$(echo $eth0_ip | sed 's/\.[0-9]*$/.1/')
-
-eth1_network=$(echo $eth1_ip | sed 's/\.[0-9]*$/.0/')
-eth1_broadcast=$(echo $eth1_ip | sed 's/\.[0-9]*$/.255/')
-
-# Ping test gateway to check connectivity if not using DHCP:
+# Configure static interface address
 if [ -z "$dhcp" ]; then
-  /sbin/ifconfig eth0 inet $eth0_ip netmask 0xffffff00 up
+  netmask="255.255.255.0"
+  eth0_network=$(echo $eth0_ip | sed 's/\.[0-9]*$/.0/')
+  eth0_broadcast=$(echo $eth0_ip | sed 's/\.[0-9]*$/.255/')
+  eth0_gateway=$(echo $eth0_ip | sed 's/\.[0-9]*$/.1/')
+
   /bin/ping -c 1 $eth0_gateway 2>&1 > /dev/null
   if [ $? -ne 0 ] ; then
     echo "ERROR: Cannot ping default gateway ($eth0_gateway)."
@@ -109,16 +116,12 @@ if [ -z "$dhcp" ]; then
     exit=1
   fi
   if [ $exit ] ; then exit $exit ; fi
+fi
 
-# Do distro specific actions:
-
-case $distro in
-CentOS)
-
-hostname $fqdn
+#=====================================================================
+function build_centos {
 
 # Write /etc/sysconfig/network.
-
 cat > /etc/sysconfig/network <<EOF
 NETWORKING=yes
 NETWORKING_IPV6=yes
@@ -127,7 +130,7 @@ GATEWAY=${eth0_gateway}
 EOF
 
 # Write /etc/sysconfig/network-scripts/ifcfg-eth0.
-if [ $dhcp == 'on' ]; then
+if [ $dhcp ]; then
 cat > /etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
 DEVICE=eth0
 BOOTPROTO=dhcp
@@ -143,43 +146,23 @@ ONBOOT=yes
 EOF
 fi
 
-if [[ ${eth1_ip} != "" ]] ; then
-cat > /etc/sysconfig/network-scripts/ifcfg-eth1 <<EOF
-DEVICE=eth1
-BOOTPROTO=static
-IPADDR=${eth1_ip}
-NETMASK=${netmask}
-ONBOOT=yes
-EOF
-fi
-
-if [ $maintain_ip == 'off' ]; then
-    /etc/init.d/network restart
-fi
-
 # Install Puppet agent:
-/bin/rpm -ivh http://yum.puppetlabs.com/el/5/products/i386/puppetlabs-release-5-6.noarch.rpm
+/bin/rpm -ivh /tmp/$PUPPET_REPO #http://yum.puppetlabs.com/el/5/products/i386/puppetlabs-release-5-6.noarch.rpm
 /usr/bin/yum -y install puppet
 
-;;
-Ubuntu)
+}
 
-domain=`echo ${fqdn} | sed 's/^[^.]*\.//'`
+#=====================================================================
+function build_ubuntu {
 
-if [ $dhcp == 'on' ]; then
+if [ $dhcp ]; then
 cat > /etc/network/interfaces <<EOF
 auto lo eth0
 iface lo inet loopback
-
 iface eth0 inet dhcp
-  dns-search ${domain}
-  dns-domain ${domain}
 EOF
 else
 cat > /etc/network/interfaces <<EOF
-# This file describes the network interfaces available on your system
-# and how to activate them. For more information, see interfaces(5).
-
 # The loopback network interface
 auto lo
 iface lo inet loopback
@@ -189,28 +172,12 @@ auto eth0
 iface eth0 inet static
   address ${eth0_ip}
   netmask ${netmask}
-  network ${eth0_network}
-  broadcast ${eth0_broadcast}
   gateway ${eth0_gateway}
-  dns-nameservers ${ns1} ${ns2}
-  dns-search ${domain}
-  dns-domain ${domain}
-EOF
-fi
-
-if [[ $eth1_ip != "" ]] ; then
-  cat >> /etc/network/interfaces <<EOF
-
-auto eth1
-iface eth1 inet static
-  address ${eth1_ip}
-  netmask ${netmask}
-  network ${eth1_network}
-  broadcast ${eth1_broadcast}
 EOF
 fi
 
 # Built a real resolv.conf without dnsmasq
+domain=`echo ${fqdn} | sed 's/^[^.]*\.//'`
 rm /etc/resolv.conf
 cat > /etc/resolv.conf << EOF
 domain ${domain}
@@ -221,22 +188,8 @@ if [ ! -z "$ns2" ] ; then
   echo "nameserver ${ns2}" >> /etc/resolv.conf
 fi
 
-echo $hostname > /etc/hostname
-
-if [ $maintain_ip == 'off' ]; then
-    /usr/bin/killall dhclient3
-    /etc/init.d/networking restart
-fi
-
-/bin/hostname -F /etc/hostname
-
 # Install puppet
 curl --silent ${PUPPET_URL}/pubkey.gpg | apt-key add - > /dev/null
-/usr/bin/wget -O /tmp/$PUPPET_REPO $PUPPET_URL/$PUPPET_REPO
-if [ "$?" != "0" ]; then
-  echo "ERROR: unable to get $PUPPET_URL/$PUPPET_REPO"
-  exit 1
-fi
 /usr/bin/dpkg -i /tmp/$PUPPET_REPO
 
 # Make apt-get install really really silently.
@@ -244,27 +197,40 @@ APT_OPTS='-qq -y'
 export DEBIAN_FRONTEND=noninteractive
 echo 'Dpkg::Options{"--force-confdef";"--force-confold";}' >> /etc/apt/apt.conf.d/local
 
-/usr/bin/apt-get update
-/usr/bin/apt-get dist-upgrade
-/usr/bin/apt-get install puppet
+/usr/bin/apt-get $APT_OPTS update
+/usr/bin/apt-get $APT_OPTS dist-upgrade
+/usr/bin/apt-get $APT_OPTS install puppet
 
-# Install additional packages:
-/usr/bin/apt-get install git
+# echo "START=yes" > /etc/default/puppet
+}
 
-echo "START=yes" > /etc/default/puppet
+#=====================================================================
+# Do distro specific actions:
 
-;;
+hostname $fqdn
+echo $fqdn > /etc/hostname
+
+# Download puppet
+/usr/bin/wget -O /tmp/$PUPPET_REPO $PUPPET_URL/$PUPPET_REPO
+if [ "$?" != "0" ]; then
+  echo "ERROR: unable to get $PUPPET_URL/$PUPPET_REPO"
+  exit 1
+fi
+
+case $distro in
+CentOS) build_centos ;;
+Ubuntu) build_ubuntu ;;
 *)
-
 echo "Distribution not supported - update script to support the distro you want to bootstrap."
 exit 1
-
 ;;
 esac
 
-if [ ! -z "$puppetmaster" ] ; then
-  puppetmaster='puppet'
+if [ $ssh_keygen ] ; then
+  rm /etc/ssh/ssh_host*key*
+  ssh-keygen -A
 fi
+
 cat > /etc/puppet/puppet.conf <<EOF
 [main]
 logdir=/var/log/puppet
@@ -292,7 +258,5 @@ mv $hosts_tmp /etc/hosts
 # Run puppet as a service
 
 echo "All done!"
-) 2>&1 | /usr/bin/tee /root/bootstrap-linux.log
-
-echo "Start puppet 'puppet agent -t'"
+echo "Start puppet: 'puppet agent -t'"
 echo "And sign the host certificate on the puppet master."
